from typing import Protocol

from app.config import load_runtime_config
from app.repositories.memory_store import store as memory_store


class StoreProtocol(Protocol):
    def get_user(self, *args, **kwargs): ...
    def get_user_by_email(self, *args, **kwargs): ...
    def create_user(self, *args, **kwargs): ...
    def list_tasks(self, *args, **kwargs): ...
    def get_task(self, *args, **kwargs): ...
    def create_task(self, *args, **kwargs): ...
    def update_task(self, *args, **kwargs): ...
    def soft_delete_task(self, *args, **kwargs): ...
    def list_fixed_events(self, *args, **kwargs): ...
    def get_fixed_event(self, *args, **kwargs): ...
    def create_fixed_event(self, *args, **kwargs): ...
    def update_fixed_event(self, *args, **kwargs): ...
    def soft_delete_fixed_event(self, *args, **kwargs): ...
    def create_execution_log(self, *args, **kwargs): ...
    def list_execution_logs(self, *args, **kwargs): ...
    def save_generated_schedule(self, *args, **kwargs): ...
    def get_latest_generated_schedule(self, *args, **kwargs): ...
    def list_generated_schedules(self, *args, **kwargs): ...
    def get_generated_schedule_history_item(self, *args, **kwargs): ...
    def update_generated_schedule_title(self, *args, **kwargs): ...
    def soft_delete_generated_schedule(self, *args, **kwargs): ...
    def reset_demo_data(self, *args, **kwargs): ...


_mysql_store: StoreProtocol | None = None


def get_store() -> StoreProtocol:
    if load_runtime_config().data_store != "mysql":
        return memory_store

    global _mysql_store
    if _mysql_store is None:
        from app.repositories.mysql_store import MySqlStore

        _mysql_store = MySqlStore()
    return _mysql_store
